### ISSUE TITLE
It breaks when you call an non-existing page

### ISSUE THREAD

**Issue by hdf1986** [Wolox/wor-paginate#48]
For example when accesing to page 4, but you have just 3 pages. it throws:
```
NoMethodError: undefined method `map' for nil:NilClass
```

**Comment by sebasdeldi** [comment]
I have not been able to reproduce this bug.

- Ruby version: 2.4.0p0 (2016-12-24 revision 57164) 


- Rails version: 5.1.6.1

Output:
`{
    "page": [],
    "count": 0,
    "total_pages": 2000,
    "total_count": 50000,
    "current_page": 2010,
    "next_page": null
}`

Please consider closing this issue or give further explanation of it.
