### ISSUE TITLE
Optional max limit

### ISSUE THREAD

**Issue by fedeest** [Wolox/wor-paginate#58]
Hacer que el max_limit que se usa para paginar, pueda ser seteado desde el cliente que usa la gema.

Se debería poder usar el método `render_paginated` de la siguiente manera:

```
class Controller
  def method1
    render_paginated(x, x)
  end

  def method2
    render_paginated(y, y, max_limit)
  end
end
```
Tal que, el en endpoint `method1` se devolverán a lo sumo los productos que estén configurados en 
```
Wor::Paginate::Config::DEFAULTS_CONFIGS[:max_limit]
```
 y en `method2` a lo sumo `max_limit`.

Agregar la documentación de como utilizar este nuevo parámetro al README.

**Comment by mnmallea** [comment]
Closed  in #63
